# This is a basic workflow to help you get started with Actions

name: cem

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          - ad: Ekip Çalışması GitHub Sync
  # Kesin taahhüde veya sürüme sabitleyebilirsiniz.
  # kullanımlar: Ekip çalışması/github-sync@42dcac69eb5a41fad0d518efeb6aecf1e45f8d01
  kullanım alanları: Ekip çalışması/github-sync@v1.3.3
  ile:
    # GitHub belirteci
    GITHUB_TOKEN:
    # Ekip çalışması URI'sı
    TEAMWORK_URI:
    # Takım çalışması API belirteci
    TEAMWORK_API_TOKEN:
    # Otomatik etiketlemeyi etkinleştirmek istiyor musunuz: doğru/yanlış
    AUTOMATIC_TAGGING: # isteğe bağlı
    # PR açıldıktan sonra görevin taşınmasını istediğiniz sütunun büyük/küçük harfe duyarlı sütun adı
    BOARD_COLUMN_OPENED: # isteğe bağlı, varsayılan
    # PR birleştirildikten sonra görevin taşınmasını istediğiniz sütunun büyük/küçük harfe duyarlı sütun adı
    BOARD_COLUMN_MERGED: # isteğe bağlı, varsayılan
    # PR birleştirilmeden kapatılmışsa, görevin taşınmasını istediğiniz sütunun büyük/küçük harfe duyarlı sütun adı
    BOARD_COLUMN_CLOSED: # isteğe bağlı, varsayılan
          echo test, and deploy your project.
